version: '3'

services:
  api:
    build: .
    env_file:
      - .env
    depends_on:
      - rabbitmq
    entrypoint: gunicorn --bind 0.0.0.0:8000 "app:create_app()"
    ports:
      - "8000:8000"

  celery_worker:
    restart: always
    build: .
    command: celery -A app.worker worker --loglevel=DEBUG
    depends_on:
      - rabbitmq
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

